// export const INFURA_ID = process.env.NEXT_PUBLIC_INFURA_ID || "f8ba1bb00c3843e7a827531f00a15e10";
export const INFURA_ID = process.env.NEXT_PUBLIC_INFURA_ID || "ce3bb5830c2c42528f7555ef9642d171";

export const ETHERSCAN_KEY = "MPP68TAVE5UMYN1V1MVS266D3DAHP7RH6E";

export const BLOCK_NATIVE_KEY = "6a5ab061-4863-476c-8a99-a7d8428b5bfc";

export const DEFAULT_POLL_TIME_BALANCE = 30000;
export const DEFAULT_POLL_TIME_PROVIDER = 30000;
export const DEFAULT_POLL_TIME_ALLOCATION_DECODER = 30000;
export const DEFAULT_POLL_TIME_ALLOCATION_ORDER_TX = 30000;
export const DEFAULT_POLL_TIME_RESOURCE = 30000;
export const DEFAULT_POLL_TIME_CONTRACT_READER = 30000;
export const DEFAULT_POLL_TIME_EXCHANGE_PRICE = 30000;
export const DEFAULT_POLL_TIME_GAS_PRICE = 30000;

export const DAI_ADDRESS = "0x6B175474E89094C44Da98b954EedeAC495271d0F";

export const NETWORKS = {
  localhost: {
    name: "localhost",
    color: "#666666",
    chainId: 31337,
    blockExplorer: "",
    rpcUrl: "http://localhost:8545",
  },
  mainnet: {
    name: "mainnet",
    color: "#ff8b9e",
    chainId: 1,
    rpcUrl: `wss://mainnet.infura.io/ws/v3/${INFURA_ID}`,
    blockExplorer: "https://etherscan.io/",
  },
  rinkeby: {
    name: "rinkeby",
    color: "#e0d068",
    chainId: 4,
    rpcUrl: `wss://rinkeby.infura.io/ws/v3/${INFURA_ID}`,
    faucet: "https://faucet.rinkeby.io/",
    blockExplorer: "https://rinkeby.etherscan.io/",
  },
  ropsten: {
    name: "ropsten",
    color: "#F60D09",
    chainId: 3,
    faucet: "https://faucet.ropsten.be/",
    blockExplorer: "https://ropsten.etherscan.io/",
    rpcUrl: `wss://ropsten.infura.io/ws/v3/${INFURA_ID}`,
  },
  goerli: {
    name: "goerli",
    color: "#0975F6",
    chainId: 5,
    faucet: "https://goerli-faucet.slock.it/",
    blockExplorer: "https://goerli.etherscan.io/",
    rpcUrl: `https://goerli.infura.io/v3/${INFURA_ID}`,
  },
  xdai: {
    name: "xdai",
    color: "#48a9a6",
    chainId: 100,
    price: 1,
    gasPrice: 1000000000,
    rpcUrl: "https://dai.poa.network",
    faucet: "https://xdai-faucet.top/",
    blockExplorer: "https://blockscout.com/poa/xdai/",
  },
};

export const Product = {
  RareHeroPack: 0,
  EpicHeroPack: 1,
  LegendaryHeroPack: 2,
  PetPack: 3,
  EnergyToken: 4,
  BasicGuildToken: 5,
  Tier1GuildToken: 6,
  Tier2GuildToken: 7,
  Tier3GuildToken: 8,
};

export const Rarity = {
  Rare: 0,
  Epic: 1,
  Legendary: 2,
  Common: 3,
  NA: 4,
};

export const TX_STATUS = {
  MINING: "MINING",
  PROCESSING: "PROCESSING",
  DONE: "DONE",
};

const gatewayUrl = "https://gateway.pinata.cloud/ipfs/Qmb4zXXazuFrv3Fr399sCFT6WvNcSegYS935AjrP4ZPXgD/";
export const HeroesMetadata = [
  {
    id: 1,
    name: "Lia",
    tagline: "Priestess of Illumination",
    faction: "Glade",
    class: "Mage",
    type: "Light",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Lia",
    warrior: "Warrior Lia",
    elite: "Elite Lia",
    mythic: "Mythic Lia",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Lia/Summoning_Hero_Lia_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Lia/Summoning_Hero_Lia_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Lia/Summoning_Hero_Lia_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Lia/Summoning_Hero_Lia_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Lia/CollectionAsset_Hero_Lia_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Lia/CollectionAsset_Hero_Lia_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Lia/CollectionAsset_Hero_Lia_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Lia/CollectionAsset_Hero_Lia_Mythic.mp4`,
  },
  {
    id: 2,
    name: "Strider",
    tagline: "Untamed Huntress",
    faction: "Glade",
    class: "Ranged",
    type: "Earth",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Strider",
    warrior: "Warrior Strider",
    elite: "Elite Strider",
    mythic: "Mythic Strider",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Strider/Summoning_Hero_Strider_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Strider/Summoning_Hero_Strider_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Strider/Summoning_Hero_Strider_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Strider/Summoning_Hero_Strider_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Strider/CollectionAsset_Hero_Strider_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Strider/CollectionAsset_Hero_Strider_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Strider/CollectionAsset_Hero_Strider_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Strider/CollectionAsset_Hero_Strider_Mythic.mp4`,
  },
  {
    id: 3,
    name: "Tavros",
    tagline: "Archmage of Darkness",
    faction: "Empire",
    class: "Mage",
    type: "Dark",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Tavros",
    warrior: "Warrior Tavros",
    elite: "Elite Tavros",
    mythic: "Mythic Tavros",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Tavros/Summoning_Hero_Tavros_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Tavros/Summoning_Hero_Tavros_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Tavros/Summoning_Hero_Tavros_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Tavros/Summoning_Hero_Tavros_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Tavros/CollectionAsset_Hero_Tavros_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Tavros/CollectionAsset_Hero_Tavros_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Tavros/CollectionAsset_Hero_Tavros_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Tavros/CollectionAsset_Hero_Tavros_Mythic.mp4`,
  },
  {
    id: 4,
    name: "Tomoe",
    tagline: "The Wandering Blade",
    faction: "Empire",
    class: "Melee",
    type: "Light",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Tomoe",
    warrior: "Warrior Tomoe",
    elite: "Elite Tomoe",
    mythic: "Mythic Tomoe",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Tomoe/Summoning_Hero_Tomoe_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Tomoe/Summoning_Hero_Tomoe_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Tomoe/Summoning_Hero_Tomoe_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Tomoe/Summoning_Hero_Tomoe_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Tomoe/CollectionAsset_Hero_Tomoe_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Tomoe/CollectionAsset_Hero_Tomoe_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Tomoe/CollectionAsset_Hero_Tomoe_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Tomoe/CollectionAsset_Hero_Tomoe_Mythic.mp4`,
  },
  {
    id: 5,
    name: "Arkus",
    tagline: "Hallowed Champion",
    faction: "Empire",
    class: "Melee",
    type: "Light",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Arkus",
    warrior: "Warrior Arkus",
    elite: "Elite Arkus",
    mythic: "Mythic Arkus",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Arkus/Summoning_Hero_Arkus_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Arkus/Summoning_Hero_Arkus_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Arkus/Summoning_Hero_Arkus_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Arkus/Summoning_Hero_Arkus_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Arkus/CollectionAsset_Hero_Arkus_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Arkus/CollectionAsset_Hero_Arkus_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Arkus/CollectionAsset_Hero_Arkus_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Arkus/CollectionAsset_Hero_Arkus_Mythic.mp4`,
  },
  {
    id: 6,
    name: "Germain",
    tagline: "Swashbuckling Charmer",
    faction: "Glade",
    class: "Melee",
    type: "Light",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Germain",
    warrior: "Warrior Germain",
    elite: "Elite Germain",
    mythic: "Mythic Germain",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Germain/Summoning_Hero_Germain_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Germain/Summoning_Hero_Germain_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Germain/Summoning_Hero_Germain_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Germain/Summoning_Hero_Germain_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Germain/CollectionAsset_Hero_Germain_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Germain/CollectionAsset_Hero_Germain_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Germain/CollectionAsset_Hero_Germain_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Germain/CollectionAsset_Hero_Germain_Mythic.mp4`,
  },
  {
    id: 7,
    name: "Akhun",
    tagline: "Prince of Light",
    faction: "Empire",
    class: "Melee",
    type: "Light",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Akhun",
    warrior: "Warrior Akhun",
    elite: "Elite Akhun",
    mythic: "Mythic Akhun",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Akhun/Summoning_Hero_Akhun_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Akhun/Summoning_Hero_Akhun_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Akhun/Summoning_Hero_Akhun_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Akhun/Summoning_Hero_Akhun_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Akhun/CollectionAsset_Hero_Akhun_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Akhun/CollectionAsset_Hero_Akhun_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Akhun/CollectionAsset_Hero_Akhun_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Akhun/CollectionAsset_Hero_Akhun_Mythic.mp4`,
  },
  {
    id: 8,
    name: "Aria",
    tagline: "Keeper of Mystery",
    faction: "Empire",
    class: "Mage",
    type: "Dark",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Aria",
    warrior: "Warrior Aria",
    elite: "Elite Aria",
    mythic: "Mythic Aria",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Aria/Summoning_Hero_Aria_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Aria/Summoning_Hero_Aria_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Aria/Summoning_Hero_Aria_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Aria/Summoning_Hero_Aria_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Aria/CollectionAsset_Hero_Aria_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Aria/CollectionAsset_Hero_Aria_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Aria/CollectionAsset_Hero_Aria_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Aria/CollectionAsset_Hero_Aria_Mythic.mp4`,
  },
  {
    id: 9,
    name: "Ewindel",
    tagline: "The Luminous Weaver",
    faction: "Horde",
    class: "Mage",
    type: "Light",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Ewindel",
    warrior: "Warrior Ewindel",
    elite: "Elite Ewindel",
    mythic: "Mythic Ewindel",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Ewindel/Summoning_Hero_Ewindel_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Ewindel/Summoning_Hero_Ewindel_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Ewindel/Summoning_Hero_Ewindel_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Ewindel/Summoning_Hero_Ewindel_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Ewindel/CollectionAsset_Hero_Ewindel_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Ewindel/CollectionAsset_Hero_Ewindel_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Ewindel/CollectionAsset_Hero_Ewindel_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Ewindel/CollectionAsset_Hero_Ewindel_Mythic.mp4`,
  },
  {
    id: 10,
    name: "Kanreh",
    tagline: "Grassland Protector",
    faction: "Glade",
    class: "Melee",
    type: "Earth",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Kanreh",
    warrior: "Warrior Kanreh",
    elite: "Elite Kanreh",
    mythic: "Mythic Kanreh",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Kanreh/Summoning_Hero_Kanreh_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Kanreh/Summoning_Hero_Kanreh_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Kanreh/Summoning_Hero_Kanreh_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Kanreh/Summoning_Hero_Kanreh_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Kanreh/CollectionAsset_Hero_Kanreh_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Kanreh/CollectionAsset_Hero_Kanreh_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Kanreh/CollectionAsset_Hero_Kanreh_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Kanreh/CollectionAsset_Hero_Kanreh_Mythic.mp4`,
  },
  {
    id: 11,
    name: "Miera",
    tagline: "Gatekeeper of Otherrealm",
    faction: "Glade",
    class: "Mage",
    type: "Dark",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Miera",
    warrior: "Warrior Miera",
    elite: "Elite Miera",
    mythic: "Mythic Miera",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Miera/Summoning_Hero_Miera_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Miera/Summoning_Hero_Miera_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Miera/Summoning_Hero_Miera_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Miera/Summoning_Hero_Miera_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Miera/CollectionAsset_Hero_Miera_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Miera/CollectionAsset_Hero_Miera_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Miera/CollectionAsset_Hero_Miera_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Miera/CollectionAsset_Hero_Miera_Mythic.mp4`,
  },
  {
    id: 12,
    name: "Othrox",
    tagline: "Lost Prince of Draconia",
    faction: "Horde",
    class: "Melee",
    type: "Fire",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Othrox",
    warrior: "Warrior Othrox",
    elite: "Elite Othrox",
    mythic: "Mythic Othrox",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Othrox/Summoning_Hero_Othrox_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Othrox/Summoning_Hero_Othrox_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Othrox/Summoning_Hero_Othrox_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Othrox/Summoning_Hero_Othrox_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Othrox/CollectionAsset_Hero_Othrox_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Othrox/CollectionAsset_Hero_Othrox_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Othrox/CollectionAsset_Hero_Othrox_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Othrox/CollectionAsset_Hero_Othrox_Mythic.mp4`,
  },
  {
    id: 13,
    name: "Prielle",
    tagline: "Light of the North",
    faction: "Empire",
    class: "Mage",
    type: "Light",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Prielle",
    warrior: "Warrior Prielle",
    elite: "Elite Prielle",
    mythic: "Mythic Prielle",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Prielle/Summoning_Hero_Prielle_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Prielle/Summoning_Hero_Prielle_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Prielle/Summoning_Hero_Prielle_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Prielle/Summoning_Hero_Prielle_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Prielle/CollectionAsset_Hero_Prielle_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Prielle/CollectionAsset_Hero_Prielle_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Prielle/CollectionAsset_Hero_Prielle_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Prielle/CollectionAsset_Hero_Prielle_Mythic.mp4`,
  },
  {
    id: 14,
    name: "Ulmak",
    tagline: "Revenant of Dust",
    faction: "Horde",
    class: "Melee",
    type: "Earth",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Ulmak",
    warrior: "Warrior Ulmak",
    elite: "Elite Ulmak",
    mythic: "Mythic Ulmak",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Ulmak/Summoning_Hero_Ulmak_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Ulmak/Summoning_Hero_Ulmak_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Ulmak/Summoning_Hero_Ulmak_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Ulmak/Summoning_Hero_Ulmak_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Ulmak/CollectionAsset_Hero_Ulmak_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Ulmak/CollectionAsset_Hero_Ulmak_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Ulmak/CollectionAsset_Hero_Ulmak_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Ulmak/CollectionAsset_Hero_Ulmak_Mythic.mp4`,
  },
  {
    id: 15,
    name: "Gwynn",
    tagline: "Oracle of the Infinite",
    faction: "Glade",
    class: "Melee",
    type: "Water",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Gwynn",
    warrior: "Warrior Gwynn",
    elite: "Elite Gwynn",
    mythic: "Mythic Gwynn",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Gwynn/Summoning_Hero_Gwynn_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Gwynn/Summoning_Hero_Gwynn_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Gwynn/Summoning_Hero_Gwynn_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Gwynn/Summoning_Hero_Gwynn_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Gwynn/CollectionAsset_Hero_Gwynn_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Gwynn/CollectionAsset_Hero_Gwynn_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Gwynn/CollectionAsset_Hero_Gwynn_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Gwynn/CollectionAsset_Hero_Gwynn_Mythic.mp4`,
  },
  {
    id: 16,
    name: "Umbar",
    tagline: "Bringer of Despair",
    faction: "Horde",
    class: "Melee",
    type: "Dark",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Umbar",
    warrior: "Warrior Umbar",
    elite: "Elite Umbar",
    mythic: "Mythic Umbar",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Umbar/Summoning_Hero_Umbar_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Umbar/Summoning_Hero_Umbar_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Umbar/Summoning_Hero_Umbar_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Umbar/Summoning_Hero_Umbar_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Umbar/CollectionAsset_Hero_Umbar_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Umbar/CollectionAsset_Hero_Umbar_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Umbar/CollectionAsset_Hero_Umbar_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Umbar/CollectionAsset_Hero_Umbar_Mythic.mp4`,
  },
  {
    id: 17,
    name: "Morax",
    tagline: "Forsaken Demon",
    faction: "Horde",
    class: "Mage",
    type: "Fire",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Morax",
    warrior: "Warrior Morax",
    elite: "Elite Morax",
    mythic: "Mythic Morax",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Morax/Summoning_Hero_Morax_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Morax/Summoning_Hero_Morax_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Morax/Summoning_Hero_Morax_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Morax/Summoning_Hero_Morax_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Morax/CollectionAsset_Hero_Morax_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Morax/CollectionAsset_Hero_Morax_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Morax/CollectionAsset_Hero_Morax_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Morax/CollectionAsset_Hero_Morax_Mythic.mp4`,
  },
  {
    id: 18,
    name: "Farrah",
    tagline: "Shadow Assassin",
    faction: "Horde",
    class: "Ranged",
    type: "Earth",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Farrah",
    warrior: "Warrior Farrah",
    elite: "Elite Farrah",
    mythic: "Mythic Farrah",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Farrah/Summoning_Hero_Farrah_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Farrah/Summoning_Hero_Farrah_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Farrah/Summoning_Hero_Farrah_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Farrah/Summoning_Hero_Farrah_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Farrah/CollectionAsset_Hero_Farrah_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Farrah/CollectionAsset_Hero_Farrah_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Farrah/CollectionAsset_Hero_Farrah_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Farrah/CollectionAsset_Hero_Farrah_Mythic.mp4`,
  },
  {
    id: 19,
    name: "Varik",
    tagline: "Infamous Thief",
    faction: "Horde",
    class: "Melee",
    type: "Water",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Varik",
    warrior: "Warrior Varik",
    elite: "Elite Varik",
    mythic: "Mythic Varik",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Varik/Summoning_Hero_Varik_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Varik/Summoning_Hero_Varik_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Varik/Summoning_Hero_Varik_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Varik/Summoning_Hero_Varik_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Varik/CollectionAsset_Hero_Varik_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Varik/CollectionAsset_Hero_Varik_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Varik/CollectionAsset_Hero_Varik_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Varik/CollectionAsset_Hero_Varik_Mythic.mp4`,
  },
  {
    id: 20,
    name: "Rufus",
    tagline: "Guardian of the Skies",
    faction: "Glade",
    class: "Ranged",
    type: "Water",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Rufus",
    warrior: "Warrior Rufus",
    elite: "Elite Rufus",
    mythic: "Mythic Rufus",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Rufus/Summoning_Hero_Rufus_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Rufus/Summoning_Hero_Rufus_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Rufus/Summoning_Hero_Rufus_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Rufus/Summoning_Hero_Rufus_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Rufus/CollectionAsset_Hero_Rufus_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Rufus/CollectionAsset_Hero_Rufus_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Rufus/CollectionAsset_Hero_Rufus_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Rufus/CollectionAsset_Hero_Rufus_Mythic.mp4`,
  },
  {
    id: 21,
    name: "Rei",
    tagline: "Inferno's Dancer",
    faction: "Glade",
    class: "Melee",
    type: "Light",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Rei",
    warrior: "Warrior Rei",
    elite: "Elite Rei",
    mythic: "Mythic Rei",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Rei/Summoning_Hero_Rei_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Rei/Summoning_Hero_Rei_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Rei/Summoning_Hero_Rei_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Rei/Summoning_Hero_Rei_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Rei/CollectionAsset_Hero_Rei_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Rei/CollectionAsset_Hero_Rei_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Rei/CollectionAsset_Hero_Rei_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Rei/CollectionAsset_Hero_Rei_Mythic.mp4`,
  },
  {
    id: 22,
    name: "Tieroc",
    tagline: "Cursed Sorcerer",
    faction: "Glade",
    class: "Mage",
    type: "Dark",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Tieroc",
    warrior: "Warrior Tieroc",
    elite: "Elite Tieroc",
    mythic: "Mythic Tieroc",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Tieroc/Summoning_Hero_Tieroc_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Tieroc/Summoning_Hero_Tieroc_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Tieroc/Summoning_Hero_Tieroc_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Tieroc/Summoning_Hero_Tieroc_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Tieroc/CollectionAsset_Hero_Tieroc_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Tieroc/CollectionAsset_Hero_Tieroc_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Tieroc/CollectionAsset_Hero_Tieroc_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Tieroc/CollectionAsset_Hero_Tieroc_Mythic.mp4`,
  },
  {
    id: 23,
    name: "Duren",
    tagline: "The Dark Hand",
    faction: "Glade",
    class: "Melee",
    type: "Dark",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Duren",
    warrior: "Warrior Duren",
    elite: "Elite Duren",
    mythic: "Mythic Duren",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Duren/Summoning_Hero_Duren_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Duren/Summoning_Hero_Duren_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Duren/Summoning_Hero_Duren_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Duren/Summoning_Hero_Duren_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Duren/CollectionAsset_Hero_Duren_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Duren/CollectionAsset_Hero_Duren_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Duren/CollectionAsset_Hero_Duren_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Duren/CollectionAsset_Hero_Duren_Mythic.mp4`,
  },
  {
    id: 24,
    name: "Elohatt",
    tagline: "Exiled Necromancer",
    faction: "Horde",
    class: "Mage",
    type: "Water",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Elohatt",
    warrior: "Warrior Elohatt",
    elite: "Elite Elohatt",
    mythic: "Mythic Elohatt",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Elohatt/Summoning_Hero_Elohatt_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Elohatt/Summoning_Hero_Elohatt_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Elohatt/Summoning_Hero_Elohatt_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Elohatt/Summoning_Hero_Elohatt_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Elohatt/CollectionAsset_Hero_Elohatt_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Elohatt/CollectionAsset_Hero_Elohatt_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Elohatt/CollectionAsset_Hero_Elohatt_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Elohatt/CollectionAsset_Hero_Elohatt_Mythic.mp4`,
  },
  {
    id: 25,
    name: "Rowan",
    tagline: "Sentinel of the Wald",
    faction: "Glade",
    class: "Mage",
    type: "Dark",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Rowan",
    warrior: "Warrior Rowan",
    elite: "Elite Rowan",
    mythic: "Mythic Rowan",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Rowan/Summoning_Hero_Rowan_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Rowan/Summoning_Hero_Rowan_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Rowan/Summoning_Hero_Rowan_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Rowan/Summoning_Hero_Rowan_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Rowan/CollectionAsset_Hero_Rowan_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Rowan/CollectionAsset_Hero_Rowan_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Rowan/CollectionAsset_Hero_Rowan_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Rowan/CollectionAsset_Hero_Rowan_Mythic.mp4`,
  },
  {
    id: 26,
    name: "Felicia",
    tagline: "Volcanic Nymph",
    faction: "Glade",
    class: "Mage",
    type: "Fire",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Felicia",
    warrior: "Warrior Felicia",
    elite: "Elite Felicia",
    mythic: "Mythic Felicia",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Felicia/Summoning_Hero_Felicia_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Felicia/Summoning_Hero_Felicia_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Felicia/Summoning_Hero_Felicia_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Felicia/Summoning_Hero_Felicia_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Felicia/CollectionAsset_Hero_Felicia_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Felicia/CollectionAsset_Hero_Felicia_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Felicia/CollectionAsset_Hero_Felicia_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Felicia/CollectionAsset_Hero_Felicia_Mythic.mp4`,
  },
  {
    id: 27,
    name: "Kalix",
    tagline: "King of the Frostmire",
    faction: "Glade",
    class: "Melee",
    type: "Water",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Kalix",
    warrior: "Warrior Kalix",
    elite: "Elite Kalix",
    mythic: "Mythic Kalix",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Kalix/Summoning_Hero_Kalix_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Kalix/Summoning_Hero_Kalix_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Kalix/Summoning_Hero_Kalix_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Kalix/Summoning_Hero_Kalix_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Kalix/CollectionAsset_Hero_Kalix_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Kalix/CollectionAsset_Hero_Kalix_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Kalix/CollectionAsset_Hero_Kalix_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Kalix/CollectionAsset_Hero_Kalix_Mythic.mp4`,
  },
  {
    id: 28,
    name: "Torim",
    tagline: "Dwarven Battlemaster",
    faction: "Empire",
    class: "Ranged",
    type: "Earth",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Torim",
    warrior: "Warrior Torim",
    elite: "Elite Torim",
    mythic: "Mythic Torim",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Torim/Summoning_Hero_Torim_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Torim/Summoning_Hero_Torim_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Torim/Summoning_Hero_Torim_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Torim/Summoning_Hero_Torim_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Torim/CollectionAsset_Hero_Torim_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Torim/CollectionAsset_Hero_Torim_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Torim/CollectionAsset_Hero_Torim_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Torim/CollectionAsset_Hero_Torim_Mythic.mp4`,
  },
  {
    id: 29,
    name: "Helia",
    tagline: "Princess of Flame",
    faction: "Horde",
    class: "Ranged",
    type: "Fire",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Helia",
    warrior: "Warrior Helia",
    elite: "Elite Helia",
    mythic: "Mythic Helia",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Helia/Summoning_Hero_Helia_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Helia/Summoning_Hero_Helia_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Helia/Summoning_Hero_Helia_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Helia/Summoning_Hero_Helia_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Helia/CollectionAsset_Hero_Helia_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Helia/CollectionAsset_Hero_Helia_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Helia/CollectionAsset_Hero_Helia_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Helia/CollectionAsset_Hero_Helia_Mythic.mp4`,
  },
  {
    id: 30,
    name: "Freia",
    tagline: "Bastion of Defense",
    faction: "Empire",
    class: "Melee",
    type: "Earth",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Freia",
    warrior: "Warrior Freia",
    elite: "Elite Freia",
    mythic: "Mythic Freia",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Freia/Summoning_Hero_Freia_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Freia/Summoning_Hero_Freia_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Freia/Summoning_Hero_Freia_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Freia/Summoning_Hero_Freia_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Freia/CollectionAsset_Hero_Freia_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Freia/CollectionAsset_Hero_Freia_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Freia/CollectionAsset_Hero_Freia_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Freia/CollectionAsset_Hero_Freia_Mythic.mp4`,
  },
  {
    id: 31,
    name: "Kharkuk",
    tagline: "Chieftan of the Deadlands",
    faction: "Horde",
    class: "Melee",
    type: "Earth",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Kharkuk",
    warrior: "Warrior Kharkuk",
    elite: "Elite Kharkuk",
    mythic: "Mythic Kharkuk",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Kharkuk/Summoning_Hero_Kharkuk_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Kharkuk/Summoning_Hero_Kharkuk_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Kharkuk/Summoning_Hero_Kharkuk_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Kharkuk/Summoning_Hero_Kharkuk_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Kharkuk/CollectionAsset_Hero_Kharkuk_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Kharkuk/CollectionAsset_Hero_Kharkuk_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Kharkuk/CollectionAsset_Hero_Kharkuk_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Kharkuk/CollectionAsset_Hero_Kharkuk_Mythic.mp4`,
  },
  {
    id: 32,
    name: "Daskah",
    tagline: "Notorious Brigand",
    faction: "Horde",
    class: "Ranged",
    type: "Fire",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Daskah",
    warrior: "Warrior Daskah",
    elite: "Elite Daskah",
    mythic: "Mythic Daskah",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Daskah/Summoning_Hero_Daskah_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Daskah/Summoning_Hero_Daskah_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Daskah/Summoning_Hero_Daskah_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Daskah/Summoning_Hero_Daskah_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Daskah/CollectionAsset_Hero_Daskah_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Daskah/CollectionAsset_Hero_Daskah_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Daskah/CollectionAsset_Hero_Daskah_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Daskah/CollectionAsset_Hero_Daskah_Mythic.mp4`,
  },
  {
    id: 33,
    name: "Cyrus",
    tagline: "Infernal Swordsman",
    faction: "Empire",
    class: "Melee",
    type: "Dark",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Cyrus",
    warrior: "Warrior Cyrus",
    elite: "Elite Cyrus",
    mythic: "Mythic Cyrus",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Cyrus/Summoning_Hero_Cyrus_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Cyrus/Summoning_Hero_Cyrus_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Cyrus/Summoning_Hero_Cyrus_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Cyrus/Summoning_Hero_Cyrus_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Cyrus/CollectionAsset_Hero_Cyrus_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Cyrus/CollectionAsset_Hero_Cyrus_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Cyrus/CollectionAsset_Hero_Cyrus_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Cyrus/CollectionAsset_Hero_Cyrus_Mythic.mp4`,
  },
  {
    id: 34,
    name: "Takati",
    tagline: "The Stonewalker",
    faction: "Horde",
    class: "Melee",
    type: "Water",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Takati",
    warrior: "Warrior Takati",
    elite: "Elite Takati",
    mythic: "Mythic Takati",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Takati/Summoning_Hero_Takati_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Takati/Summoning_Hero_Takati_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Takati/Summoning_Hero_Takati_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Takati/Summoning_Hero_Takati_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Takati/CollectionAsset_Hero_Takati_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Takati/CollectionAsset_Hero_Takati_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Takati/CollectionAsset_Hero_Takati_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Takati/CollectionAsset_Hero_Takati_Mythic.mp4`,
  },
  {
    id: 35,
    name: "Tikor",
    tagline: "Herald of Violence",
    faction: "Horde",
    class: "Melee",
    type: "Water",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    forSale: "TRUE",
    normal: "Tikor",
    warrior: "Warrior Tikor",
    elite: "Elite Tikor",
    mythic: "Mythic Tikor",
    animationSummoningNormal: `${gatewayUrl}Content/Summoning/Heroes/Tikor/Summoning_Hero_Tikor_Base.mp4`,
    animationSummoningWarrior: `${gatewayUrl}Content/Summoning/Heroes/Tikor/Summoning_Hero_Tikor_Warrior.mp4`,
    animationSummoningElite: `${gatewayUrl}Content/Summoning/Heroes/Tikor/Summoning_Hero_Tikor_Epic.mp4`,
    animationSummoningMythic: `${gatewayUrl}Content/Summoning/Heroes/Tikor/Summoning_Hero_Tikor_Mythic.mp4`,
    animationDetailNormal: `${gatewayUrl}Content/CollectionAssets/Heroes/Tikor/CollectionAsset_Hero_Tikor_Base.mp4`,
    animationDetailWarrior: `${gatewayUrl}Content/CollectionAssets/Heroes/Tikor/CollectionAsset_Hero_Tikor_Warrior.mp4`,
    animationDetailElite: `${gatewayUrl}Content/CollectionAssets/Heroes/Tikor/CollectionAsset_Hero_Tikor_Epic.mp4`,
    animationDetailMythic: `${gatewayUrl}Content/CollectionAssets/Heroes/Tikor/CollectionAsset_Hero_Tikor_Mythic.mp4`,
  },
];

export const PetsMetadata = [
  {
    id: 1,
    name: "Trixie",
    type: "Workers",
    rarity: "Common",
    assetFile: "https://via.placeholder.com/350",
    probability: "20.00%",
    effect: "Free daily cubelets",
    effect2: "T1 + T2",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Trixie/Summoning_Pet_Trixie.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Trixie/CollectionAsset_Pet_Trixie.mp4`,
  },
  {
    id: 2,
    name: "Krios",
    type: "Workers",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    probability: "9.00%",
    effect: "Free daily cubelets",
    effect2: "T2 + T3",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Krios/Summoning_Pet_Krios.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Krios/CollectionAsset_Pet_Krios.mp4`,
  },
  {
    id: 3,
    name: "Namur",
    type: "Workers",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    probability: "3.33%",
    effect: "Free daily cubelets",
    effect2: "T3 + T4",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Namur/Summoning_Pet_Namur.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Namur/CollectionAsset_Pet_Namur.mp4`,
  },
  {
    id: 4,
    name: "Cadmus",
    type: "Workers",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    probability: "1.00%",
    effect: "Free daily cubelets",
    effect2: "T4 + T5",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Cadmus/Summoning_Pet_Cadmus.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Cadmus/CollectionAsset_Pet_Cadmus.mp4`,
  },
  {
    id: 5,
    name: "Reina",
    type: "Scouts",
    rarity: "Common",
    assetFile: "https://via.placeholder.com/350",
    probability: "20.00%",
    effect: "Increase item drop rates",
    effect2: "10%",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Reina/Summoning_Pet_Reina.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Reina/CollectionAsset_Pet_Reina.mp4`,
  },
  {
    id: 6,
    name: "Stype",
    type: "Scouts",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    probability: "9.00%",
    effect: "Increase item drop rates",
    effect2: "25%",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Stype/Summoning_Pet_Stype.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Stype/CollectionAsset_Pet_Stype.mp4`,
  },
  {
    id: 7,
    name: "Onyx",
    type: "Scouts",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    probability: "3.33%",
    effect: "Increase item drop rates",
    effect2: "50%",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Onyx/Summoning_Pet_Onyx.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Onyx/CollectionAsset_Pet_Onyx.mp4`,
  },
  {
    id: 8,
    name: "Selene",
    type: "Scouts",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    probability: "1.00%",
    effect: "Increase item drop rates",
    effect2: "100%",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Selene/Summoning_Pet_Selene.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Selene/CollectionAsset_Pet_Selene.mp4`,
  },
  {
    id: 9,
    name: "Rummus",
    type: "Hunters",
    rarity: "Common",
    assetFile: "https://via.placeholder.com/350",
    probability: "20.00%",
    effect: "Increase cubelet rewards",
    effect2: "T1-T2",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Rummus/Summoning_Pet_Rummus.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Rummus/CollectionAsset_Pet_Rummus.mp4`,
  },
  {
    id: 10,
    name: "Urska",
    type: "Hunters",
    rarity: "Rare",
    assetFile: "https://via.placeholder.com/350",
    probability: "9.00%",
    effect: "Increase cubelet rewards",
    effect2: "T1-T3",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Urska/Summoning_Pet_Urska.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Urska/CollectionAsset_Pet_Urska.mp4`,
  },
  {
    id: 11,
    name: "Mbeku",
    type: "Hunters",
    rarity: "Epic",
    assetFile: "https://via.placeholder.com/350",
    probability: "3.33%",
    effect: "Increase cubelet rewards",
    effect2: "T1-T4",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Mbeku/Summoning_Pet_Mbeku.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Mbeku/CollectionAsset_Pet_Mbeku.mp4`,
  },
  {
    id: 12,
    name: "Lucius",
    type: "Hunters",
    rarity: "Legendary",
    assetFile: "https://via.placeholder.com/350",
    probability: "1.00%",
    effect: "Increase cubelet rewards",
    effect2: "All Tiers",
    animationSummoning: `${gatewayUrl}Content/Summoning/Pets/Lucius/Summoning_Pet_Lucius.mp4`,
    animationDetail: `${gatewayUrl}Content/CollectionAssets/Pets/Lucius/CollectionAsset_Pet_Lucius.mp4`,
  },
];
